/**
 * Canonical import field names → CSV header synonyms (human / Excel exports).
 */

import type { CsvColumnAliases } from "./csv-import-utils.js";

/** Fields we may read from PO CSV rows (required subset validated separately). */
export const PO_CSV_CANONICAL_FIELDS = [
  "po_number",
  "supplier_name",
  "line_number",
  "item_description",
  "qty",
  "unit",
  "unit_price",
  "plant",
  "pt",
  "delivery_location",
  "incoterm_location",
  "kawasan_berikat",
  "currency",
] as const;

export const PO_CSV_ALIASES: CsvColumnAliases = {
  po_number: [
    "po number",
    "po num",
    "po no",
    "purchase order",
    "purchase order number",
    "purchase order #",
    "order number",
    "po_number",
  ],
  supplier_name: ["supplier name", "supplier", "vendor name", "vendor", "supplier_name"],
  line_number: ["line number", "line no", "line", "po line", "line_number", "lineno"],
  item_description: ["item description", "description", "item", "item desc", "material", "item_description"],
  qty: ["qty", "quantity", "order qty"],
  unit: ["unit", "uom", "unit of measure"],
  unit_price: ["unit price", "price", "value", "unit_price", "unit cost"],
  plant: ["plant", "plant code"],
  pt: ["pt", "entity", "company code", "legal entity"],
  delivery_location: ["delivery location", "delivery", "ship to", "warehouse", "delivery_location"],
  incoterm_location: ["incoterm location", "incoterms", "incoterm", "incoterm_location"],
  kawasan_berikat: ["kawasan berikat", "bonded zone", "kb", "kawasan_berikat"],
  currency: ["currency", "curr", "ccy"],
};

/**
 * Shipment CSV template header row: shipment-only fields (no duplicate PO header fields).
 * Supplier, incoterm, PT, plant, and currency come from the linked PO when omitted.
 */
export const SHIPMENT_CSV_TEMPLATE_HEADER_ORDER = [
  "PO number",
  "Line number",
  "Qty delivered",
  "BM %",
  "PPN %",
  "PPH %",
  "Forwarder / liner",
  "Ship via (Sea / Air)",
  "Origin port name",
  "Origin port country",
  "Destination port name",
  "Destination port country",
  "ETD",
  "ETA",
  "ATD",
  "ATA",
  "Product classification type",
  "PIB type",
  "PIB Doc No",
  "Nopen",
  "Nopen date",
  "BL/AWB",
  "Insurance No",
  "COO (Certificate of Origin)",
  "CBM",
  "Freight charges",
  "Net weight (MT)",
  "Gross weight (MT)",
  "Total Invoice amount",
  "BM (total)",
  "PPN (total)",
  "PPH (total)",
  "PDRI (total)",
  "Delivered at",
  "Invoice no.",
  "Currency rate",
  "Remarks (optional)",
] as const;

/** Canonical field → shipment detail label (for errors and docs). */
export const SHIPMENT_CSV_CANONICAL_TO_DETAIL_LABEL: Record<string, string> = {
  shipment_no: "Shipment number",
  po_number: "PO number",
  intake_id: "Intake ID",
  line_number: "Line number",
  delivered_qty: "Qty delivered",
  vendor_name: "Vendor / supplier",
  forwarder_name: "Forwarder / liner",
  pt: "PT",
  plant: "Plant",
  incoterm: "Incoterm",
  shipment_method: "Ship via (Sea / Air)",
  origin_port_name: "Origin port name",
  origin_port_country: "Origin port country",
  destination_port_name: "Destination port name",
  destination_port_country: "Destination port country",
  etd: "ETD",
  eta: "ETA",
  atd: "ATD",
  ata: "ATA",
  product_classification: "Product classification type",
  pib_type: "PIB type",
  no_request_pib: "PIB Doc No",
  nopen: "Nopen",
  nopen_date: "Nopen date",
  bl_awb: "BL/AWB",
  insurance_no: "Insurance No",
  coo: "COO (Certificate of Origin)",
  cbm: "CBM",
  incoterm_amount: "Freight charges",
  net_weight_mt: "Net weight (MT)",
  gross_weight_mt: "Gross weight (MT)",
  total_po_amount: "Total Invoice amount",
  bm_percentage: "BM %",
  ppn_percentage: "PPN %",
  pph_percentage: "PPH %",
  bm: "BM (total)",
  ppn_amount: "PPN (total)",
  pph_amount: "PPH (total)",
  pdri: "PDRI (total)",
  delivered_at: "Delivered at",
  currency: "Currency",
  invoice_no: "Invoice no.",
  currency_rate: "Currency rate",
  remarks: "Remarks (optional)",
};

export const SHIPMENT_CSV_CANONICAL_FIELDS = [
  "shipment_no",
  "po_number",
  "intake_id",
  "line_number",
  "delivered_qty",
  "bm_percentage",
  "ppn_percentage",
  "pph_percentage",
  "vendor_name",
  "forwarder_name",
  "pt",
  "plant",
  "incoterm",
  "shipment_method",
  "origin_port_name",
  "origin_port_country",
  "destination_port_name",
  "destination_port_country",
  "etd",
  "eta",
  "atd",
  "ata",
  "product_classification",
  "pib_type",
  "no_request_pib",
  "nopen",
  "nopen_date",
  "bl_awb",
  "insurance_no",
  "coo",
  "cbm",
  "incoterm_amount",
  "net_weight_mt",
  "gross_weight_mt",
  "total_po_amount",
  "bm",
  "ppn_amount",
  "pph_amount",
  "pdri",
  "delivered_at",
  "currency",
  "invoice_no",
  "currency_rate",
  "remarks",
] as const;

export const SHIPMENT_CSV_ALIASES: CsvColumnAliases = {
  shipment_no: [
    "Shipment number",
    "shipment number",
    "shipment no",
    "shipment id",
    "shipment_no",
    "shp no",
  ],
  po_number: [
    "PO number",
    "po number",
    "po num",
    "po no",
    "purchase order",
    "purchase order number",
    "purchase order #",
    "order number",
    "po_number",
  ],
  intake_id: [
    "Intake ID",
    "intake id",
    "intake ID",
    "po intake id",
    "po uuid",
    "intake uuid",
    "intake_id",
  ],
  line_number: ["Line number", "line number", "line no", "line", "po line", "line_number"],
  delivered_qty: [
    "Qty delivered",
    "qty delivered",
    "delivered qty",
    "delivered quantity",
    "delivery qty",
    "received qty",
    "received quantity",
    "received_qty",
    "delivered_qty",
  ],
  vendor_name: [
    "Vendor / supplier",
    "vendor / supplier",
    "vendor name",
    "vendor",
    "supplier name",
    "supplier",
    "vendor_name",
  ],
  forwarder_name: [
    "Forwarder / liner",
    "forwarder / liner",
    "forwarder name",
    "forwarder",
    "forwarder_name",
  ],
  pt: ["PT", "pt", "entity", "company code"],
  plant: ["Plant", "plant", "plant code"],
  incoterm: ["Incoterm", "incoterm", "incoterms"],
  shipment_method: [
    "Ship via (Sea / Air)",
    "ship via (sea / air)",
    "Ship via (Air / Sea)",
    "ship via (air / sea)",
    "shipment method",
    "mode",
    "ship mode",
    "shipment_method",
  ],
  origin_port_name: ["Origin port name", "origin port name", "origin port", "pol", "origin_port_name"],
  origin_port_country: ["Origin port country", "origin port country", "origin country", "origin_port_country"],
  destination_port_name: [
    "Destination port name",
    "destination port name",
    "destination port",
    "pod",
    "destination_port_name",
  ],
  destination_port_country: [
    "Destination port country",
    "destination port country",
    "destination country",
    "destination_port_country",
  ],
  etd: ["ETD", "etd", "est departure", "estimated departure", "ETD (Est. time departure)"],
  eta: ["ETA", "eta", "est arrival", "estimated arrival", "ETA (Est. time arrival)"],
  atd: ["ATD", "atd", "actual departure", "ATD (actual departure)"],
  ata: ["ATA", "ata", "actual arrival", "ATA (actual arrival)"],
  product_classification: [
    "Product classification type",
    "product classification type",
    "product classification",
    "hs code",
    "product_classification",
  ],
  pib_type: ["PIB type", "pib type", "pib", "pib_type"],
  no_request_pib: ["PIB Doc No", "pib doc no", "no request pib", "request pib", "no_request_pib"],
  nopen: ["Nopen", "nopen", "no pen"],
  nopen_date: ["Nopen date", "nopen date", "nopen_date"],
  bl_awb: ["BL/AWB", "bl/awb", "bl awb", "bl", "awb", "house bl", "bl_awb"],
  insurance_no: ["Insurance No", "insurance no", "insurance", "insurance_no"],
  coo: ["COO (Certificate of Origin)", "coo (certificate of origin)", "coo", "country of origin"],
  cbm: ["CBM", "cbm"],
  incoterm_amount: ["Freight charges", "freight charges", "incoterm amount", "service charge", "incoterm_amount"],
  net_weight_mt: ["Net weight (MT)", "net weight (mt)", "net weight mt", "net weight", "net_weight_mt"],
  gross_weight_mt: ["Gross weight (MT)", "gross weight (mt)", "gross weight mt", "gross weight", "gross_weight_mt"],
  total_po_amount: [
    "Total Invoice amount",
    "total invoice amount",
    "total po amount",
    "po amount",
    "total_po_amount",
  ],
  bm_percentage: ["BM %", "bm %", "bm percentage", "bm_percentage"],
  ppn_percentage: ["PPN %", "ppn %", "ppn percentage", "ppn_percentage"],
  pph_percentage: ["PPH %", "pph %", "pph percentage", "pph_percentage"],
  bm: ["BM (total)", "bm (total)", "bm total", "BM total", "bm"],
  ppn_amount: ["PPN (total)", "ppn (total)", "ppn total", "PPN total", "ppn_amount"],
  pph_amount: ["PPH (total)", "pph (total)", "pph total", "PPH total", "pph_amount"],
  pdri: ["PDRI (total)", "pdri (total)", "Total PDRI", "total PDRI", "total pdri", "PDRI", "pdri"],
  delivered_at: ["Delivered at", "delivered at", "delivery date", "delivered_at"],
  currency: ["Currency", "currency", "curr"],
  invoice_no: ["Invoice no.", "invoice no", "invoice", "invoice_no"],
  currency_rate: ["Currency rate", "currency rate", "fx rate", "exchange rate", "currency_rate"],
  remarks: ["Remarks (optional)", "remarks (optional)", "remarks", "notes", "comment"],
};
